export { default as Form } from "./Form/Form";
export { default as Posts } from "./Posts/Posts";
export { default as Post } from "./Post/Post";
export { default as Header } from "./Header/Header";
export { default as Comments } from "./Comments/Comments";
export { default as Comment } from "./Comment/Comment";
export { default as User } from "./User/User";
export { default as Sidebar } from "./Sidebar/Sidebar";
export { default as Person } from "./Person/Person";
