const constants = {
  SET_USER: "SET_USER",
  SET_USERS: "SET_USERS",
  SET_MESSAGES: "SET_MESSAGES",
  SET_POSTS: "SET_POSTS",
  SET_HASH_TAGS: "SET_HASH_TAGS",
  SET_LIKES: "SET_LIKES",
  SET_FLEETS: "SET_FLEETS",
  SET_BANNERS: "SET_BANNERS",
  SET_PROFILE_TAB: "SET_PROFILE_TAB",
  SET_PROFILES: "SET_PROFILES",
  SET_TAGED_PHOTOS: "SET_TAGED_PHOTOS",
};

export default constants;
