const constants = {
  SET_USER: "SET_USER",
  SET_USERS: "SET_USERS",
  SET_MESSAGES: "SET_MESSAGES",
  SET_POSTS: "SET_POSTS",
  SET_HASH_TAGS: "SET_HASH_TAGS",
  SET_LIKES: "SET_LIKES",
  SET_FLEETS: "SET_FLEETS",
};

export default constants;
